sudo: required
services:
  - docker

before_install:
  - docker build -t doliveros/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true doliveros/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-rest"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-507856266964"
  bucket_path: "docker-rest"
  on:
    branch: master
  access_key_id:
   secure: $AWS_ACCESS_KEY
  secret_access_key:
   secure: "$AWS_SECRET_KEY" 
